#!/usr/bin/env bash
set -e

use_remote=""
if [ ! -z "$1" ];
then
    use_remote="$1"
else
    echo "No remotes given, looking for them..."
    all_remotes="$(git remote show)"
    num_remotes=$(echo ${all_remotes} | wc -w | tr -d ' ')
    if [ ${num_remotes} -ne 1 ]
        then
            echo "Need exactly one remote, found ${num_remotes}"
            echo ${all_remotes}
            exit 2
    fi
    use_remote="$all_remotes"
fi

remote_branch_name=""
if [ ! -z "$2" ];
then
    remote_branch_name="$2"
else
    echo "Finding target branch on remote $use_remote"
    remote_branch_name="$(git remote show ${use_remote} | grep 'HEAD branch' | rev | cut -f 1 -d ' ' | rev)"
    [ $? -ne 0 ] && exit 1
fi

remote_branch="${use_remote}/${remote_branch_name}"

# Remove all branches that are merged with origin/master, including local master!
echo "Finding merged branches..."
git branch --list --merged ${remote_branch} | tr -ds ' ' '' | grep -v '*' | xargs git branch -d

echo "Finding squash-merged branches..."
# Code copied from https://stackoverflow.com/a/56026209
git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do
    mergeBase=$(git merge-base ${remote_branch} $branch) &&
        [[ $(git cherry ${remote_branch} $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]] &&
        git branch -D $branch || true
done
echo "Done!"
